name: football
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.6 #
  logger: ^2.3.0
  flutter_svg: ^2.0.10+1
  dio: ^5.5.0+1
  get: ^4.6.6
  get_storage:
  smooth_page_indicator: ^1.1.0
  intl: ^0.17.0
  share_plus: ^6.3.1
  image_picker: ^1.1.2
  mime: ^1.0.0
  mask_text_input_formatter: ^2.9.0
  firebase_messaging: ^15.0.4
  firebase_core: ^3.3.0
  flutter_local_notifications: ^17.0.1
  flutter_xlider: ^3.4.0
  http: ^1.2.2
  cached_network_image: ^3.3.1
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/intro/
    - assets/images/team/
    - assets/images/home/
    - assets/images/bottom_navigation/
    - assets/images/settings/
    - assets/images/test/
    - assets/images/balance/
    - assets/images/transfer/
    - assets/poppins/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/poppins/Poppins-Regular.ttf
        #- asset: poppins/Poppins-ExtraBoldItalic.ttf

